'use client';

import { useEffect, useState, use } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import api from '@/lib/axios';
import Sidebar from '@/components/Sidebar';
import { useSidebarStore } from '@/store/sidebarStore';
import { BrainCircuit, Play, CheckCircle2, XCircle, ArrowRight, ArrowLeft } from 'lucide-react';

interface Question {
  question: string;
  options: string[];
  correctAnswerIndex: number;
}

export default function ExamPage({ params }: { params: Promise<{ subjectId: string }> }) {
  const { subjectId } = use(params);
  const router = useRouter();
  const { isOpen } = useSidebarStore();
  
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState<number | null>(null);
  const [passed, setPassed] = useState(false);
  const [subject, setSubject] = useState<any>(null);
  const [generationTime, setGenerationTime] = useState(0);

  const loadingFacts = [
    "AI is analyzing your course curriculum...",
    "Brainstorming unique multiple-choice questions...",
    "Ensuring the difficulty level is just right...",
    "Checking your progress records...",
    "Syncing with the Knowledge Base...",
    "Almost there! Finalizing your exam structure..."
  ];
  const [currentFactIdx, setCurrentFactIdx] = useState(0);

  useEffect(() => {
    let interval: any;
    if (generating) {
      setGenerationTime(15);
      setCurrentFactIdx(0);
      interval = setInterval(() => {
        setGenerationTime(prev => Math.max(0, prev - 1));
        setCurrentFactIdx(prev => (prev + 1) % loadingFacts.length);
      }, 2000);
    } else {
      setGenerationTime(0);
    }
    return () => clearInterval(interval);
  }, [generating]);

  useEffect(() => {
    // Fetch subject to get title
    api.get(`/subjects/${subjectId}`).then(res => setSubject(res.data)).catch(console.error);
  }, [subjectId]);

  const handleGenerate = async () => {
    setGenerating(true);
    setQuestions([]); // Clear old questions to show loading state
    try {
      const res = await api.post(`/ai/exam/generate/${subjectId}`);
      setQuestions(res.data.questions);
      setAnswers({});
      setSubmitted(false);
      setScore(null);
    } catch (err) {
      console.error('Failed to generate exam', err);
      alert('Failed to generate exam. Is your Gemini API key valid?');
    } finally {
      setGenerating(false);
    }
  };

  const handleSelect = (qIdx: number, aIdx: number) => {
    if (submitted) return;
    setAnswers(prev => ({ ...prev, [qIdx]: aIdx }));
  };

  const handleSubmit = async () => {
    if (Object.keys(answers).length < questions.length) {
      alert('Please answer all questions before submitting.');
      return;
    }

    setLoading(true);
    let correctCount = 0;
    questions.forEach((q, idx) => {
      if (answers[idx] === q.correctAnswerIndex) {
        correctCount++;
      }
    });

    const finalScore = Math.round((correctCount / questions.length) * 100);
    setScore(finalScore);

    try {
      const res = await api.post(`/ai/exam/submit/${subjectId}`, { score: finalScore });
      setPassed(res.data.passed);
    } catch (err) {
      console.error('Failed to submit exam', err);
    } finally {
      setSubmitted(true);
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-4 md:p-8 pt-8 relative z-10 animate-in fade-in duration-700">
          
          <Link href={`/subjects/${subjectId}`} className="inline-flex items-center space-x-2 text-gray-400 hover:text-white mb-8 transition-colors">
            <ArrowLeft size={20} />
            <span>Back to Course</span>
          </Link>

          <div className="mb-12">
            <div className="flex items-center space-x-3 mb-4 text-indigo-400">
              <BrainCircuit size={24} />
              <h2 className="text-sm font-bold tracking-widest uppercase">AI-Powered Assessment</h2>
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight mb-4">
              Certification Exam
            </h1>
            <p className="text-gray-400 text-lg leading-relaxed max-w-2xl">
              You've completed the videos for {subject?.title || 'this course'}. Now, prove your knowledge. This exam is dynamically generated by our AI based strictly on the course curriculum. Pass with 70% or higher to unlock your official certificate.
            </p>
          </div>

          {!questions.length ? (
            <div className="bg-white/[0.02] border border-white/10 rounded-[3rem] p-12 text-center backdrop-blur-xl">
              <div className="w-24 h-24 bg-indigo-500/10 rounded-full flex items-center justify-center mx-auto mb-8 ring-1 ring-indigo-500/30">
                <BrainCircuit size={40} className="text-indigo-400" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-4">Ready when you are!</h3>
              <p className="text-gray-400 mb-8 max-w-md mx-auto">
                10 dynamically generated multiple-choice questions. No two exams are exactly alike.
              </p>
              <button 
                onClick={handleGenerate}
                disabled={generating}
                className="inline-flex items-center justify-center bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/50 text-white font-bold py-4 px-8 rounded-2xl transition-all shadow-lg shadow-indigo-500/20 active:scale-95 space-x-3"
              >
                {generating ? (
                  <div className="flex flex-col items-center space-y-4">
                    <div className="flex items-center space-x-3">
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>{generationTime > 0 ? `Generating... (${generationTime}s)` : 'Finalizing...'}</span>
                    </div>
                    <p className="text-[10px] text-indigo-400 uppercase tracking-widest font-black animate-pulse">
                      {loadingFacts[currentFactIdx]}
                    </p>
                  </div>
                ) : (
                  <>
                    <Play size={20} />
                    <span>Start Exam</span>
                  </>
                )}
              </button>
            </div>
          ) : (
            <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8">
              
              {/* Results Banner */}
              {submitted && (
                <div className={`p-8 rounded-[2rem] border backdrop-blur-md mb-12 shadow-2xl ${
                  passed 
                    ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-100 shadow-emerald-500/10' 
                    : 'bg-red-500/10 border-red-500/20 text-red-100 shadow-red-500/10'
                }`}>
                  <div className="flex items-center justify-between flex-wrap gap-6">
                    <div>
                      <h2 className={`text-3xl font-black mb-2 ${passed ? 'text-emerald-400' : 'text-red-400'}`}>
                        {passed ? 'Exam Passed!' : 'Exam Failed'}
                      </h2>
                      <p className="text-opacity-80 font-medium">
                        {passed 
                          ? 'Congratulations! You achieved the required passing score. Your certificate is now unlocked.' 
                          : 'You need at least 70% to pass. Review your answers below and try again when ready.'}
                      </p>
                    </div>
                    <div className="text-right flex items-center gap-6">
                      <div className="text-center">
                        <span className="block text-4xl font-black">{score}%</span>
                        <span className="text-xs font-bold uppercase tracking-widest opacity-60">Score</span>
                      </div>
                      
                      {passed ? (
                        <Link href={`/subjects/${subjectId}/certificate`} className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold py-3 px-6 rounded-xl transition-all flex items-center space-x-2">
                          <span>View Certificate</span>
                          <ArrowRight size={18} />
                        </Link>
                      ) : (
                        <button onClick={handleGenerate} className="bg-red-500 hover:bg-red-400 text-white font-bold py-3 px-6 rounded-xl transition-all">
                          Retake Exam
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* Questions */}
              {questions.map((q, qIdx) => (
                <div key={qIdx} className={`bg-white/[0.02] border rounded-[2rem] p-8 transition-all duration-500 ${
                  submitted 
                    ? answers[qIdx] === q.correctAnswerIndex 
                      ? 'border-emerald-500/30' 
                      : 'border-red-500/30'
                    : 'border-white/5'
                }`}>
                  <h3 className="text-xl font-bold text-white mb-6 flex gap-4">
                    <span className="text-indigo-400 font-black">{qIdx + 1}.</span>
                    <span>{q.question}</span>
                  </h3>
                  <div className="space-y-3">
                    {q.options.map((opt, aIdx) => {
                      const isSelected = answers[qIdx] === aIdx;
                      const isCorrect = q.correctAnswerIndex === aIdx;
                      
                      let btnStateClass = 'bg-white/5 border-transparent hover:bg-white/10 text-gray-300';
                      
                      if (submitted) {
                        if (isCorrect) btnStateClass = 'bg-emerald-500/20 border-emerald-500/50 text-emerald-300 ring-1 ring-emerald-500/50';
                        else if (isSelected && !isCorrect) btnStateClass = 'bg-red-500/20 border-red-500/50 text-red-300 ring-1 ring-red-500/50';
                        else btnStateClass = 'bg-white/5 border-transparent opacity-50';
                      } else if (isSelected) {
                        btnStateClass = 'bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-500/20';
                      }

                      return (
                        <button
                          key={aIdx}
                          onClick={() => handleSelect(qIdx, aIdx)}
                          disabled={submitted}
                          className={`w-full text-left px-6 py-4 rounded-xl border transition-all duration-300 flex items-center font-medium ${btnStateClass}`}
                        >
                          <div className="flex-1">{opt}</div>
                          {submitted && isCorrect && <CheckCircle2 size={20} className="text-emerald-400 ml-3" />}
                          {submitted && isSelected && !isCorrect && <XCircle size={20} className="text-red-400 ml-3" />}
                        </button>
                      );
                    })}
                  </div>
                </div>
              ))}

              {!submitted && (
                <div className="flex justify-end pt-8">
                  <button
                    onClick={handleSubmit}
                    disabled={loading || Object.keys(answers).length < questions.length}
                    className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/30 disabled:text-white/50 text-white font-bold py-4 px-12 rounded-2xl transition-all shadow-xl shadow-indigo-500/20 active:scale-95"
                  >
                    {loading ? 'Submitting...' : 'Submit Answers'}
                  </button>
                </div>
              )}
              
            </div>
          )}
    </div>
  );
}
